### ISSUE TITLE
Callback Error

### ISSUE THREAD

**Issue by patrickhrml** [PayEx/PayEx.Psp.WooCommerce#12]
PayEx receives an error when attempting to send Callback to WC. Example that was checked was a CreditCard transaction and we're receiving the response: responseCode":"BadRequest","responseMessage":"-1",

towards https://merchantsite/wc-api/wc_gateway_payex_cc/

**Comment by olegisk** [comment]
Please send woocomerce logs (located in /wp-content/uploads/wc-logs/payex_psp_*) to info@aait.se
