### ISSUE TITLE
Translation in Swedish

### ISSUE THREAD

**Issue by cechise** [PayEx/PayEx.Psp.WooCommerce#13]
I'm having issues with the swedish translation for the invoice payment. 

The term "Social security number" is not beeing translated on the checkout page. The .po-file seems to have it translated but its not showing up in the checkout. 

Language is set to Swedish in the payment method settings page.

**Comment by cechise** [comment]
Maybe i should specify. Its the label above the input-field that is not being translated.

**Comment by olegisk** [comment]
https://github.com/PayEx/PayEx.Psp.WooCommerce/commit/01dceb1c373f6f5a94d28f81df3510aef3479bde
