### ISSUE TITLE
"Unauthorized" error

### ISSUE THREAD

**Issue by sjobidoo** [PayEx/PayEx.Psp.WooCommerce#2]
I'm getting a error on the checkout form. Two lines of "Unauthorized" are showing up. 

From the log:

```
10-19-2017 @ 09:22:04 - GET https://api.externalintegration.payex.com/psp/checkout Data: array (
)
10-19-2017 @ 09:22:04 - Status code: 200
10-19-2017 @ 09:22:04 - Response: array (
  'authorized' => false,
  'paymentSession' => 'https://api.externalintegration.payex.com/psp/checkout/payment-sessions',
  'version' => '5.0.1',
)
```

I've verified that the correct token is being used.

**Comment by olegisk** [comment]
@sjobidoo I think your merchant token is invalid

**Comment by olegisk** [comment]
@sjobidoo Please note that **PayEx Checkout** was moved th another repository https://github.com/PayEx/PayEx.Checkout.WooCommerce

**Comment by sjobidoo** [comment]
The issue was solved after installing the version from the other repository.
