### ISSUE TITLE
Missing country code in MSISDN

### ISSUE THREAD

**Issue by bomyras** [PayEx/PayEx.Psp.WooCommerce#4]
It's mandatory for our customers to enter their phone number in the checkout, and using Vipps as payment method, the API returns the following error message:

{"type":"https://api.payex.com/psp/errordetail/vipps/InputError","title":"Bad Request","status":"400","instance":"2280122b-9507-51ea-b5c5-d00704db5f19","detail":"RetryWithNewData","problems":[{"name":"Payment.PrefillInfo.Msisdn","description":"The field Msisdn must match the regular expression '^(\\+47)(?:4[015-8]|5[89]|87|9\\d)\\d{6}$'"}]}

In the log, the following data is found:

    'prefillInfo' => 
    array (
      'msisdn' => '+95022797',
    ),

which indicates the country code is missing. This is verified by prepending 47 to the phone number in the checkout, and the payment is accepted.

Is it possible to make the plugin automatically prepend the country code to the phone number, without modifying the the stored version of the phone number in WooCoomerce?

**Comment by aait** [comment]
We will make a setting in admin for automatic prepend of +47, it's in the backlog
